use_frameworks!

platform :ios, '9.0'

target 'SimpleSpeedometer_Example' do
  pod 'SimpleSpeedometer', :path => '../'

  target 'SimpleSpeedometer_Tests' do
    inherit! :search_paths

    
  end
end
